# Generated by Django 5.0.2 on 2024-03-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="full_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_agent",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_buyer",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_seller",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as a admin. Must be verified prior to changing this field to True.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_farmer",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as a farmer. Must be verified prior to changing this field to True.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_partner",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be treated as a partner. Must be verified prior to changing this field to True.",
            ),
        ),
    ]
