# Generated by Django 5.0.2 on 2024-03-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("farmer", "Farmer"),
                    ("partner", "Delivery Partner"),
                    ("user", "Normal User"),
                    ("admin", "Admin"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
