# Generated by Django 5.0.2 on 2024-03-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default=1, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
