# Generated by Django 5.0.2 on 2024-03-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_user_first_name_remove_user_full_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerprofile",
            name="delivery_charge",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
