# Generated by Django 5.0.2 on 2024-03-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_partnerprofile_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partnerprofile",
            name="vehicle_license_plate",
        ),
        migrations.RemoveField(
            model_name="partnerprofile",
            name="vehicle_type",
        ),
    ]
