# Generated by Django 5.0.2 on 2024-03-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_remove_partnerprofile_vehicle_license_plate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerprofile",
            name="phone",
            field=models.CharField(
                blank=True, default=None, max_length=15, null=True, unique=True
            ),
        ),
    ]
