# Generated by Django 5.0.2 on 2024-03-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_farmerprofile_farmer_profile_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmerprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="partnerprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
