# Generated by Django 5.0.2 on 2024-03-10 02:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                ("source", models.CharField(default="online_khabar", max_length=255)),
                ("image", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="VegetableMarget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("max_price", models.CharField(max_length=255)),
                ("min_price", models.CharField(max_length=255)),
                ("average_price", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
