# Generated by Django 5.0.2 on 2024-03-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="link",
            field=models.CharField(default="/"),
        ),
    ]
