# Generated by Django 5.0.2 on 2024-04-28 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_payment_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="transaction_uuid",
        ),
    ]
