# Generated by Django 5.0.2 on 2024-05-01 05:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_remove_order_transaction_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="transaction_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
