# Generated by Django 5.0.2 on 2024-05-03 11:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_order_transaction_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
