# Generated by Django 5.0.2 on 2024-03-23 03:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fruits", "Fruits"),
                            ("vegetables", "Vegetables"),
                            ("grains", "Grains"),
                            ("dairy", "Dairy"),
                            ("meat", "Meat"),
                            ("poultry", "Poultry"),
                            ("eggs", "Eggs"),
                            ("fish", "Fish"),
                            ("herbs", "Herbs"),
                            ("spices", "Spices"),
                            ("flowers", "Flowers"),
                            ("plants", "Plants"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=100,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity_available", models.PositiveIntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("kg", "Kilogram"),
                            ("g", "Gram"),
                            ("l", "Liter"),
                            ("ml", "Milliliter"),
                            ("unit", "Unit"),
                            ("bunch", "Bunch"),
                            ("other", "Other"),
                        ],
                        default="unit",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        default="https://t4.ftcdn.net/jpg/02/29/75/83/360_F_229758328_7x8jwCwjtBMmC6rgFzLFhZoEpLobB6L8.webp",
                        null=True,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("is_organic", models.BooleanField(default=False)),
                ("harvest_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("out_of_stock", "Out of Stock"),
                            ("deleted", "Deleted"),
                            ("expired", "Expired"),
                        ],
                        default="available",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
