# Generated by Django 5.0.2 on 2024-04-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="text",
            new_name="review",
        ),
        migrations.AddField(
            model_name="review",
            name="rating_value",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Rating",
        ),
    ]
